### ISSUE TITLE
Scoring System

### ISSUE THREAD

**Issue by dustdustinthewind** [PulsarcGame/Pulsarc#35]
Prototype Scoring System in comments below: https://github.com/PulsarcGame/Pulsarc/issues/35#issuecomment-515413622

There has been some discussion on how the scoring system should work.

Should it have a capped score similar to games like osu!m, Cytus, Voez, etc.?

SolaEclipse on Discord has suggested an interesting idea using note weight (difficulty of each individual note) to determine scoring: https://docs.google.com/document/d/1ZjkfgjaOBINM0MbBADu9luXhESnKN1HJ0W5W0i31aJg/edit?usp=sharing

One aspect of the scoring system that has been heavily discussed is how combo should be used. Some people think combo should be weighed heavily, others think it shouldn't count for as much.
I think combo should be a part of the scoring, but it shouldn't be a dominant factor of the score, like how it becomes a multiplier in osu and Intralism. This is too punishing of a system in my opinion, and focuses much more on combo/speed than acc.

**Comment by jaanjah** [comment]
Perhaps next time you should still try to make the issue as informative as possible, instead of making it and adding it "later".

**Comment by Adrriii** [comment]
Current implemented scoring system : 

A hidden combo is used instead of the displayed combo
- It is capped to 50
- MAX gives 2 combo, Perfect gives 1, Great does not change it, Good removes 8, Bad removes 30, Miss resets the combo.
- Each arc hit score is directly multipied by this combo
- At the beginning of the map, you start at full combo (50)

The maximum score of a map is determined by this formula : 
`maxMapScore = numberOfObjects * maxJudgeScore * maxCombo`
maxJudgeScore is 320 and maxCombo is 50.

The maximum displayed score of a map will always be 1,000,000, determined by this formula : 
`displayScore = currentScore / maxMapScore  * maxDisplayedScore`
maxMapScore is determined depending on the map as seen above, maxDisplayedScore is 1,000,000

This system is close to osu!mania in its approach, but rewards combo differently.
This is a first draft and can be improved. I improved the autoplay to make it more random, this way we can test multiple scores outcomes.

**Comment by dustdustinthewind** [comment]
> Perhaps next time you should still try to make the issue as informative as possible, instead of making it and adding it "later".

Fixed. I was a bit scrambled last night and realized I forgot to look things up for this, but I wanted at least "Score System" up as an issue. Not an excuse for being lazy though haha.
